######################################################################
#
# File name : graph_constructor_tb.do
# Created on: Mon Apr 04 13:02:43 -0500 2022
#
# Modified concatenation of graph_constructor_tb_compile.do and graph_constructor_tb_simulate.do 
# files auto generated by Vivado for 'behavioral' simulation
#
######################################################################

# graph_constructor_tb_compile.do ####################################
vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/work
vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim

vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../src/graph_constructor_package.vhd" \
"../../src/decoder.vhd" \
"../../src/spram_wrapper.vhd" \
"../../src/fifo_wrapper.vhd" \
"../../src/hit_buffer.vhd" \
"../../src/module_mapper.vhd" \
"../../src/output_manager.vhd" \
"../../src/controller.vhd" \
"./module_mapper_tb.vhd" \

# graph_constructor_tb_simulate.do ###################################
# Compile glbl module
vlog -work xil_defaultlib "../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/glbl.v"

# Simulate
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.module_mapper_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {module_mapper_wave.do}
do {module_mapper_control_wave.do}

#view wave
#view structure
#view signals

# Modelsim Preferences Setup ##################################################
TreeUpdate [SetDefaultTree]
configure wave -namecolwidth 250
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
configure wave -shortnames 1

# Cursor Setup ################################################################
WaveRestoreCursors \
{{TB: First Word} {35 ns} 1} \
{{Decode: Event Start} {45 ns} 1} \
{{Decode: Event End} {235 ns} 1} \
{{Control: R/W Toggle} {295 ns} 1} \
{{Out Mngr: Reading} {325 ns} 1} \
{{C1} {380 ns} 0} 

run 10us
WaveRestoreZoom {0 ns} {10us}

