######################################################################
#
# File name : graph_constructor_tb.do
# Created on: Mon Apr 04 13:02:43 -0500 2022
#
# Modified concatenation of graph_constructor_tb_compile.do and graph_constructor_tb_simulate.do 
# files auto generated by Vivado for 'behavioral' simulation
#
######################################################################

# Compile ####################################
vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/work
vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim

vlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib ../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../graph-constructor/graph-constructor.gen/sources_1/ip/fp_mult_add_0/sim/fp_mult_add_0.v" \
"../../graph-constructor/graph-constructor.gen/sources_1/ip/fp_sub_0/sim/fp_sub_0.v" \
"../../graph-constructor/graph-constructor.gen/sources_1/ip/fp_div_0/sim/fp_div_0.v" \
"../../graph-constructor/graph-constructor.gen/sources_1/ip/fp_gtoe_0/sim/fp_gtoe_0.v"

vcom  -93 -work xil_defaultlib  \
"../../src/graph_constructor_package.vhd" \
"../../src/decoder.vhd" \
"../../src/spram_wrapper.vhd" \
"../../src/fifo_wrapper.vhd" \
"../../src/hit_buffer.vhd" \
"../../src/module_mapper.vhd" \
"../../src/ec_input.vhd" \
"../../src/ec_pipeline.vhd" \
"../../src/ec_output.vhd" \
"../../src/edge_calc.vhd" \
"../../src/concatenator.vhd" \
"../../src/graph_constructor_top.vhd" \
"../../src/output_manager.vhd" \
"../../src/controller.vhd" \
"./graph_constructor_tb.vhd" \

# Compile glbl module
vlog -work xil_defaultlib "../../graph-constructor/graph-constructor.sim/sim_1/behav/modelsim/glbl.v"

# Simulate ###################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -L floating_point_v7_1_12 -lib xil_defaultlib xil_defaultlib.graph_constructor_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {graph_constructor_wave.do}
#do {graph_constructor_control_wave.do}

#view wave
#view structure
#view signals

# User Do File
# do {graph_constructor_tb.udo}

# Modelsim Preferences Setup ##################################################
TreeUpdate [SetDefaultTree]
configure wave -namecolwidth 250
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
configure wave -shortnames 1

# Cursor Setup ################################################################
WaveRestoreCursors \
{{TB: First Word} {35 ns} 1} \
{{Decode: Event Start} {55 ns} 1} \
{{Decode: Event End} {245 ns} 1} \
{{EC0: Write} {385 ns} 1} \
{{EC1: Write} {675 ns} 1} \
{{EC0: Read} {1485 ns} 1} \
{{CC: Write EC0} {1505 ns} 1} \
{{EC1: Read} {1695 ns} 1} \
{{CC: Write EC1} {1715 ns} 1} \
{{C1} {380 ns} 0} 

run 10us
WaveRestoreZoom {0 ns} {10us}

